-- Supabase Admin Dashboard Schema Extension
-- Run this in your Supabase SQL Editor

-- Admin Users Table (For custom authentication)
CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert the default admin user you requested:
-- Username: SoKhairibo92
-- Password: 6cc4aca9df (hashed using bcrypt)
INSERT INTO admin_users (username, password_hash, role) 
VALUES ('SoKhairibo92', '$2a$10$3rFUSn.y15./1.lKH9ofh.f0pnPHyHRAp6ejARN7qGwc40p2xKHmG', 'admin')
ON CONFLICT (username) DO NOTHING;


-- Notes Table
CREATE TABLE IF NOT EXISTS notes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Files Table (Google Drive references)
CREATE TABLE IF NOT EXISTS files (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  original_name VARCHAR(255) NOT NULL,
  drive_file_id VARCHAR(255),
  drive_link TEXT,
  shareable_link TEXT,
  mime_type VARCHAR(100),
  size_bytes BIGINT,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Events Table (Google Calendar references)
CREATE TABLE IF NOT EXISTS events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
  end_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
  google_event_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- Row Level Security (RLS) Setup
-- We use the Supabase Service Role Key on the backend to bypass RLS,
-- but we should secure them from public access via the anon key.

ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Deny all public access to admin tables
CREATE POLICY "Deny public access" ON admin_users FOR ALL USING (false);
CREATE POLICY "Deny public access" ON notes FOR ALL USING (false);
CREATE POLICY "Deny public access" ON files FOR ALL USING (false);
CREATE POLICY "Deny public access" ON events FOR ALL USING (false);
